FROM node:alpine
RUN mkdir -p /home/node/app && chown -R node:node /home/node/app
WORKDIR "/home/node/app"
USER node
COPY ./package.json ./
USER node
RUN yarn install 
COPY --chown=node:node ./ ./
USER node
CMD ["yarn", "start"]